spring.application.name=shop
# yang ada tanda # nya untuk lokal jadi gak ikut dijalankan di railway.
# spring.datasource.url=jdbc:postgresql://localhost:5432/marketplacefix 
# spring.datasource.username=macintoshhd
# spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}